version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: codecov
    versions:
    - 0.4.2
    - 0.4.3
    - 0.5.0
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"
