
image: Visual Studio 2019

version: "{build}"

environment:
  matrix:
    - RUBY_VERSION: 25
    - RUBY_VERSION: 25-x64
    - RUBY_VERSION: 26-x64
    - RUBY_VERSION: 27-x64
# FIXME: Appveyor does not support Ruby 3.0 yet
#    - RUBY_VERSION: 30-x64

cache:
  - vendor/bundle

init:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%

install:
  - bundle install --path vendor/bundle

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake -rdevkit
