
version: "{build}"

environment:
  matrix:
    - RUBY_VERSION: 24
    - RUBY_VERSION: 24-x64
    - RUBY_VERSION: 25-x64
    - RUBY_VERSION: 26-x64   

cache:
  - vendor/bundle

init:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%

install:
  - bundle install --path vendor/bundle

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - ruby -e "puts Encoding.find('filesystem')"
  - echo ch > 杨帆.pdf
  - ruby -Ku check.rb .
  - ruby check.rb .
  - chcp 65001
  - ruby -Ku check.rb .

test_script:
  - bundle exec rake -rdevkit
