require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Layout/EndOfLine:
  EnforcedStyle: lf # enforce LF line endings on all platforms

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
