dist: xenial

conditions: v1

if: branch = master OR tag IS present

os:
  - linux
  - osx

language: ruby

rvm:
  - '2.3'
  - '2.4'
  - '2.5'
  - '2.6'

before_install:
  - gem update --system
  - gem --version

script:
  - bundle exec rake
