conditions: v1

if: branch = master OR tag IS present

os:
  - linux
  - osx

language: ruby

rvm:
  - '2.3'
  - '2.4'
  - '2.5'

install:
  - bundle install --path vendor/bundle

script:
  - bundle exec rake
