# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ test ]
    tags: [ 'x[0-9]*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: check
      run: |
        echo $GITHUB_REF
        echo $GITHUB_EVENT_NAME
        echo $GITHUB_REF_TYPE
